<?php
/** @var EMS_Pay_Block_Payment_Form_Cc $this */
$_code = $this->getMethodCode();
$_cardTypes = $this->getCardTypes();
$isEnable = $this->getEnableSeparateCc();
?>
<?php if (!$isEnable): ?>
    <dt id="dt_method_<?php echo $_code ?>">
        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="Credit card" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
        <label for="p_method_<?php echo $_code ?>">Credit card</label>
    </dt>
    <dd id="dd_method_<?php echo $_code ?>">
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <?php foreach ($_cardTypes as $_cCode => $_cName): ?>
        <img src="<?php echo $this->getCardLogoPath($_cCode); ?>">
        <?php endforeach; ?>
        <p><?php echo $this->__('Pay online with %s', $this->getMethod()->getTitle()); ?></p>
    </li>
    <li>
        <label for="<?php echo $_code ?>_ems_card_type" class="required"><em>*</em><?php echo $this->__('Please choose card type') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_ems_card_type" name="payment[ems_card_type]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Please choose card type')) ?>" class="required-entry">
                <?php $_selectedCard = $this->getSelectedCardType(); ?>
                <?php foreach ($_cardTypes as $_cardCode => $_cardName): ?>
                    <option value="<?php echo $_cardCode ?>"<?php if($_cardCode == $_selectedCard): ?> selected="selected"<?php endif ?>><?php echo $_cardName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
</ul>
    </dd>
<?php else: ?>
    <?php foreach ($_cardTypes as $_cCode => $_cName): ?>
    <?php if ($_cCode == "ems_pay_cc") continue; ?>
        <dt id="dt_method_<?php echo $_code ?>">
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $_cName ?>" onclick="payment.switchMethod('<?php echo $_cCode ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> class="radio" />
            <label for="p_method_<?php echo $_code ?>"><?php echo $_cName ?></label>
        </dt>

        <dd id="dd_method_<?php echo $_code ?>">
        <div id="payment_form_<?php echo $_cCode ?>"  class="form-list" style="display:none;">
        <img src="<?php echo $this->getCardLogoPath($_cCode); ?>">
            <div class="input-box" style="display:none;">
                <select id="<?php echo $_code ?>_ems_card_type" name="payment[ems_card_type]" >
                    <option value="<?php echo $_cCode ?>" selected="selected"><?php echo $_cName ?></option>
                </select>
            </div>

        <p><?php echo $this->__('Pay online with %s', $_cName); ?></p>
        </div>
            </dd>
    <?php endforeach; ?>
<?php endif ?>






