<?php
/** @var EMS_Pay_Block_Payment_Form_Ideal $this */
$_code = $this->getMethodCode();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <img src="<?php echo $this->getLogoPath(); ?>">
        <p><?php echo $this->__('Pay online with %s', $this->getMethod()->getTitle()); ?></p>
    </li>
    <?php if ($this->isIssuingBankSelectionEnabled()):?>
    <li>
        <label for="<?php echo $_code ?>_issuing_bank" class="required"><em>*</em><?php echo $this->__('Please select issuing bank') ?></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_issuing_bank" name="payment[issuing_bank]" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Please select issuing bank')) ?>" class="required-entry">
                <?php $_selectedBank = $this->getIssuingBank(); ?>
                <?php foreach ($this->getIssuingBanks() as $_bankCode => $_bankName): ?>
                    <option value="<?php echo $_bankCode ?>"<?php if($_bankCode == $_selectedBank): ?> selected="selected"<?php endif ?>><?php echo $_bankName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php endif; ?>
</ul>
